### ISSUE TITLE
Error in Readme.md file

### ISSUE THREAD

**Issue by patelaryan7751** [JGEC-Winter-of-Code/Beginner-Repo#29]
Error in README.md file. The hyperlink of contributors.format is leading to 404 page instead it should direct to (https://github.com/JGEC-Winter-of-Code/Beginner-Repo/blob/master/Contributor.md).

**Comment by pydevsg** [comment]
@patelaryan7751 nope it isn't.
Check agian, don't just make unusual issue man.
