### ISSUE TITLE
List your Program in this Repo

### ISSUE THREAD

**Issue by vybhav72954** [JGEC-Winter-of-Code/Beginner-Repo#55]
Congratulations on your ongoing event.

In case, JWOC is a yearly initiative or you are planning to organize the event yearly, I suggest you list the Event [here](https://github.com/deepanshu1422/List-Of-Open-Source-Internships-Programs).

**Comment by pydevsg** [comment]
First of all thanks @vybhav72954 .
Yes, it is a yearly event.
I am creating a PR on the repository mentioned.

**Comment by pydevsg** [comment]
Done, thanks @vybhav72954 😄 
I am closing this issue :)
